### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Orpheusssl** [antbag-pm-pl/OreGen#1]
[Server thread/CRITICAL]: TypeError: "pocketmine\plugin\PluginManager::registerEvents(): Argument #1 ($listener) must be of type pocketmine\event\Listener, antbag\oregen\Main given, called in C:\Users\Çağatay\Desktop\tekrar\plugins\OreGen-main\src\antbag\oregen\Main.php on line 13" (EXCEPTION) in "pmsrc/src/plugin/PluginManager" at line 588
--- Stack trace ---
  #0 plugins/OreGen-main/src/antbag/oregen/Main(13): pocketmine\plugin\PluginManager->registerEvents(object antbag\oregen\Main#40705, object antbag\oregen\Main#40705)
  #1 pmsrc/src/plugin/PluginBase(118): antbag\oregen\Main->onEnable()
  #2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #3 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object antbag\oregen\Main#40705)
  #4 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41334)
  #5 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#7, string[34] C:\Users\..a..atay\Desktop\tekrar\, string[42] C:\Users\..a..atay\Desktop\tekrar\plugins\)
  #6 pmsrc/src/PocketMine(357): pocketmine\server()
  #7 pmsrc(11): require(string[78] phar://C:/Users/..a..atay/Desktop/tekrar/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[20:25:36.600] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by antbag-dev** [comment]
Fixed it download latest from poggit
